config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "property_deals#show_all"
  # post '/post-lead',to: "leads#create"
  get '/property_deals_showall', to: "property_deals#show_all"
  get '/property_deals_show_json/:id', to: "property_deals#show_json"
  # get '/spini_leads', to: "leads#show"
  resources :leads
  resources :property_deals
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lead.rb
class Lead < ApplicationRecord
	validates :phone_number,:presence => true,
                 :length => { :minimum => 10, :maximum => 20 }
  validates :name,:presence => true

  VALID_EMAIL_REGEX =  /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
			length: {maximum: 150},
			format: {with: VALID_EMAIL_REGEX}
end

app/models/property_deal.rb
class PropertyDeal < ApplicationRecord
	validates :title,:presence => true
  validates :offer_details,:presence => true
  validates :address,:presence => true
  validates :description,:presence => true
  validates :about,:presence => true
  validates :terms,:presence => true
  validates :seo_url,:presence => true
  validates :offer_img_url,:presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
	 skip_before_action :verify_authenticity_token
	 before_action :set_lead, only: [:edit, :destroy, :update, :show]
	def new
		@lead = Lead.new
	end

	def index
		@lead = Lead.paginate(:page => params[:page], :per_page => 20)
	end

	def create
		@lead = Lead.new(lead_params)

		if @lead.save
			GetspiniMailer.send_email(@lead).deliver_now
			# render json: @lead, status: :created
			redirect_to action: 'index'
		else
			render json: @lead.errors, status: :unprocessable_entity
		end
	end

	def update
		if @lead.update(lead_params)
			flash[:success] = "lead was successfully updated"
			redirect_to lead_path(@lead)
		else
			render 'edit'	
		end
	end

	def destroy
		@lead = Lead.find(params[:id])
		@lead.destroy
		redirect_to action: 'index'
	end

	def show
		
	end



	private

	def set_lead
			@lead = Lead.find(params[:id])
	end
	def lead_params
		params.require(:lead).permit(:name, :email, :phone_number, :category, :city)
	end
end

app/controllers/property_deals_controller.rb
class PropertyDealsController < ApplicationController
	 skip_before_action :verify_authenticity_token
	 before_action :set_property_deal, only: [:edit, :destroy, :update, :show]

	def new
		@property_deal = PropertyDeal.new
	end
	def create
		@property_deal = PropertyDeal.new(property_deal_params)
		if @property_deal.save
			# render json: @property_deal, status: :created
			redirect_to action: 'show_all'
		else
		 	render json: @property_deal.errors.full_messages, status: :bad_request
		end
	end

	def index
		@property_deal = PropertyDeal.all
		render json: @property_deal, status: :created
	end

	def show_all
		@property_deal = PropertyDeal.paginate(:page => params[:page], :per_page => 5)
	end

	def show_json
		@property_deal = PropertyDeal.find(params[:id])
		render json: @property_deal, status: :created
	end

	def show
		
	end
	
	def edit
	end
	
	def update
		if @property_deal.update(property_deal_params)
			flash[:success] = "property_deal was successfully updated"
			redirect_to property_deal_path(@property_deal)
		else
			render 'edit'	
		end
	end

	def destroy
		@property_deal = PropertyDeal.find(params[:id])
		@property_deal.destroy
		redirect_to action: 'show_all'
	end

	private
	def set_property_deal
			@property_deal = PropertyDeal.find(params[:id])
		end
	def property_deal_params
		params.require(:property_deal).permit(:title, :offer_details, :address, :description, :about, :terms, :seo_url, :offer_img_url, :banner_url)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GetspiniBackend</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> -->
  </head>
  <style type="text/css">
    body{
      background: #f0f0f2;
    }
    .well{
      background: #fff;
    }
    img{
      width: 100%;
    }
    .margin-tb{
      margin: 10px 0;
    }
    .pagination a{
      background: #F44336;
      color: #fff;
      padding: 8px;
    }
    .current{
      background: #00BCD4;
      color: #fff;
      padding: 8px;
    }
  </style>
  <body>
    <header>
      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="/property_deals_showall">GETSPINI</a>
          </div>
          <ul class="nav navbar-nav">
            <li class="active"><a href="/property_deals_showall">Home</a></li>
            <li><a href="/property_deals/new">Create new offer</a></li>
            <li><a href="/property_deals_showall">View all offers</a></li>
            <li><a href="/leads">Show Leads</a></li>
            <li><a href="/leads/new">Create Leads</a></li>
          </ul>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/leads/_form.html.erb
<%= form_for @lead, html: {class: "nifty_form"} do |f| %>
  <div class="row" style="padding:5px 18px;">
    <div class="">
      <div class="form-group">
        <label for="title">Name:</label>
        <%= f.text_field :name, class:'form-control', placeholder:'Enter Name',required:true  %>
      </div>
    </div>
    <div class="">
      <div class="form-group">
        <label for="title">Phone Number:</label>
        <%= f.text_field :phone_number, class:'form-control', placeholder:'Enter Phone Number',required:true  %>
      </div>
    </div>
    <div class="">
      <div class="form-group">
        <label for="title">Email:</label>
        <%= f.text_field :email, class:'form-control', placeholder:'Enter email' %>
      </div>
    </div>
    <div class="">
      <div class="form-group">
        <label for="title">TITLE:</label>
        <%= f.text_field :city, class:'form-control', placeholder:'Enter email', value:'Chennai' %>
      </div>
    </div>
    <div class="">
      <div class="form-group">
        <label for="title">TITLE:</label>
        <%= f.text_field :category, class:'form-control', placeholder:'Enter email', value:'Loans' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 box text-center">
      <%= f.submit "Submit",class:'btn btn-danger'  %>
    </div>
  </div>
  <!-- </form> --> 
  <% end %>

app/views/leads/edit.html.erb
<div class="col-md-offset-3 col-md-6 well well-xs">
  <h1 class="text-center">Edit Lead</h1>
  <%= render 'form' %>
</div>

app/views/leads/index.html.erb
<div class="well well-xs">
    <h1 class="text-center">All Leads</h1>
    <table class="table table-striped">                         
      <tr>      
        <th>Id</th>                    
        <th>Name</th>
        <th>Phone Number</th>
        <th>Email</th>
        <th>Category</th>
        <th>Date and Time</th>
        <th>Action</th>
      </tr>
    <% @lead.each do |data| %>       
      <tr>
        <td><%= data.id %></td> 
        <td><%= data.name %></td> 
        <td><%= data.phone_number %></td>  
        <td><%= data.email %></td>  
        <td><%= data.category %></td>
        <td><%= data.created_at %></td>
        <td><%= link_to "", edit_lead_path(data.id), class:"glyphicon glyphicon-chevron-left text-success" %>

            <%= link_to "", lead_path(data.id), method: :delete, data:{confirm: "Are you sure you want to delete"}, class:"glyphicon glyphicon-trash text-danger" %></td>  
      </tr>
    <% end %> 
    </table>    
    <div class="text-center">
        <%= will_paginate @lead %>
    </div>
    
</div>

app/views/leads/new.html.erb
<div class="col-md-offset-3 col-md-6 well well-xs">
  <h1 class="text-center">Create new Lead</h1>
  <%= form_for @lead, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
  <div class="row" style="padding:5px 18px;">
    <div class="">
      <div class="form-group">
        <label for="title">Name:</label>
        <%= f.text_field :name, class:'form-control', placeholder:'Enter Name',required:true  %>
      </div>
    </div>
    <div class="">
      <div class="form-group">
        <label for="title">Phone Number:</label>
        <%= f.text_field :phone_number, class:'form-control', placeholder:'Enter Phone Number',required:true  %>
      </div>
    </div>
    <div class="">
      <div class="form-group">
        <label for="title">Email:</label>
        <%= f.text_field :email, class:'form-control', placeholder:'Enter email' %>
      </div>
    </div>
    <div class="">
      <div class="form-group">
        <label for="title">TITLE:</label>
        <%= f.text_field :city, class:'form-control', placeholder:'Enter email', value:'Chennai' %>
      </div>
    </div>
    <div class="">
      <div class="form-group">
        <label for="title">TITLE:</label>
        <%= f.text_field :category, class:'form-control', placeholder:'Enter email', value:'Loans' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 box text-center">
      <%= f.submit "Submit",class:'btn btn-danger'  %>
    </div>
  </div>
  <!-- </form> --> 
  <% end %>
</div>

app/views/leads/show.html.erb
<div class="col-md-offset-3 col-md-6 well well-xs">
	
	<div class="col-md-12">
		<h1>Lead Detail</h1>
		<ul class="list-group">
			<li class="list-group-item">
				<label>Id:</label>
				<i><%= @lead.id %></i>
			</li>
			<li class="list-group-item">
				<label>Name:</label>
				<i><%= @lead.name %></i>
			</li>
			<li class="list-group-item">
				<label>Phone Number:</label>
				<i><%= @lead.phone_number %></i>
			</li>
			<li class="list-group-item">
				<label>Email:</label>
				<i><%= @lead.email %></i>
			</li>
			<li class="list-group-item">
				<label>Category:</label>
				<i><%= @lead.category %></i>
			</li>
			<li class="list-group-item">
				<label>Created At:</label>
				<i><%= @lead.created_at %></i>
			</li>
		</ul>
	</div>
</div>

app/views/property_deals/_form.html.erb
<%= form_for @property_deal, html: {class: "nifty_form"} do |f| %>
  <div class="row" style="padding:5px 18px;">
    <div class="">
      <div class="form-group">
        <label for="title">TITLE:</label>
        <%= f.text_field :title, class:'form-control', placeholder:'Enter title',required:true  %>
      </div>
    </div>
    <div class="">
      <div class="form-group">
        <label for="Offer Details">OFFER DETAILS</label>
        <%= f.text_area(:offer_details, size: '50x10', class:'form-control', placeholder:'Enter offer details') %>
      </div>
    </div>
    <div class="">
      <div class="form-group">
        <label for="Address">ADDRESS:</label>
        <%= f.text_area :address, size: '50x10', class:'form-control', placeholder:'Enter Address' ,required:true %>
      </div>
    </div>
    <div class="">
      <div class="form-group">
        <label for="Description">DESCRIPTION:</label>
        <%= f.text_area :description, size: '50x10', class:'form-control', placeholder:'Enter Description' ,required:true %>
      </div>
    </div>
    <div class="">
      <div class="form-group">
        <label for="About">ABOUT:</label>
        <%= f.text_area :about, size: '50x10', class:'form-control', placeholder:'Enter About' ,required:true %>
      </div>
    </div>
    <div class="">
      <div class="form-group">
        <label for="Terms">TERMS:</label>
        <%= f.text_area :terms, size: '50x10', class:'form-control', placeholder:'Enter Terms' ,required:true %>
      </div>
    </div>
    <div class="">
      <div class="form-group">
        <label for="Seo_url">SEO URL:</label>
        <%= f.text_field :seo_url, class:'form-control', placeholder:'Enter seo url',required:true  %>
      </div>
    </div>
    <div class="">
      <div class="form-group">
        <label for="Offer Image Url">OFFER IMAGE URL:</label>
        <%= f.text_field :offer_img_url, class:'form-control', placeholder:'Enter offer image url',required:true  %>
      </div>
    </div>
    <div class="">
      <div class="form-group">
        <label for="Banner image url">BANNER IMAGE URL:</label>
        <%= f.text_field :banner_url, class:'form-control', placeholder:'Enter banner url' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 box text-center">
      <%= f.submit "Submit",class:'btn btn-danger'  %>
    </div>
  </div>
  <!-- </form> --> 
  <% end %>

app/views/property_deals/edit.html.erb
<div class="col-md-offset-3 col-md-6 well well-xs">
  <h1 class="text-center">Create new offer</h1>
  <%= render 'form' %>
</div>

app/views/property_deals/new.html.erb
<div class="col-md-offset-3 col-md-6 well well-xs">
  <h1 class="text-center">Create new offer</h1>
  <%= render 'form' %>
</div>

app/views/property_deals/show.html.erb
<div class="col-md-offset-3 col-md-6 well well-xs">
	<div class="col-md-12 margin-tb">
		<%= image_tag ( "#{@property_deal.banner_url}") %>
	</div>
	<div class="row margin-tb">
		<div class="col-md-6">
		<%= image_tag ( "#{@property_deal.offer_img_url}") %>
		</div>
		<div class="col-md-6">
			<h4><%= @property_deal.title %></h4>
			<pre><%= @property_deal.offer_details %></pre>
		</div>
	</div>
	
	<div class="col-md-12">
		<p>
			<h4>About</h4>
			<%= @property_deal.about %>
		</p>
		<p>
			<h4>Address</h4>
			<%= @property_deal.address %>
		</p>
		<p>
			<h4>Description</h4>
			<%= @property_deal.description %>
		</p>
		<p>
			<h4>Terms</h4>
			<%= @property_deal.terms %>
		</p>
		<p>
			<h4>Seo Url</h4>
			<%= @property_deal.seo_url %>
		</p>
	</div>
</div>

app/views/property_deals/show_all.html.erb
<div class="well well-xs">
    <h1 class="text-center">All offers</h1>
    <table class="table table-striped">                         
      <tr>      
        <th>Id</th>                    
        <th>Title</th>
        <!-- <th>Offer Details</th> -->
        <!-- <th>Address</th>
        <th>Description</th>
        <th>About</th>
        <th>Terms</th> -->
        <th>Seo_Url</th>
        <!-- <th>Offer Image Url</th> -->
        <!-- <th>banner_url</th> -->
        <th>Action</th>
      </tr>
    <% @property_deal.each do |data| %>       
      <tr>
        <td><%= data.id %></td> 
        <td><%= data.title %></td> 
        <!-- <td><%= data.offer_details %></td>   -->
        <!-- <td><%= data.address %></td>   -->
        <!-- <td><%= data.description %></td>   -->
        <!-- <td><%= data.about %></td>   -->
        <!-- <td><%= data.terms %></td>   -->
        <td><%= data.seo_url %></td>  
        <!-- <td><%= data.offer_img_url %></td>   -->
        <!-- <td><%= data.banner_url %></td>  -->
        <td><%= link_to "", property_deal_path(data.id), class:"glyphicon glyphicon-chevron-left text-success" %>
            <%= link_to "", edit_property_deal_path(data.id), class:"glyphicon glyphicon-edit text-warning" %>
            <%= link_to "", property_deal_path(data.id), method: :delete, data:{confirm: "Are you sure you want to delete"}, class:"glyphicon glyphicon-trash text-danger" %></td>
      </tr>
    <% end %>                        
    </table>    
    <div class="text-center">
        <%= will_paginate @property_deal %>
    </div>
</div>